### ISSUE TITLE
Style scrollbar 

### ISSUE THREAD

**Issue by brenolasserre** [barvian/motion-number#1]
Just helping a bit :D

Current looks on Chrome: 
![image](https://github.com/user-attachments/assets/69f69adf-680e-4f59-b2bf-7abdf116733d)

Styled:
![image](https://github.com/user-attachments/assets/ae7af0d3-0e35-4c44-8a04-ff04f5192b03)

Just add this css styling: 
```
::-webkit-scrollbar {
  width: 8px;
  height: 8px;
}

::-webkit-scrollbar-track {
  background: #18181b; 
}
 
::-webkit-scrollbar-thumb {
  background: #ffffff1a; border-radius: 6px; 
}

::-webkit-scrollbar-thumb:hover {
  background: #555; cursor: pointer 
}
```

**Comment by barvian** [comment]
Looks great, thank you!!
