### ISSUE TITLE
Animation on load

### ISSUE THREAD

**Issue by dogfootruler-kr** [barvian/motion-number#4]
Hello and thank you for the library it looks awesome.

Is there a way to have the animation on page load as well? Not only when changing the value.

Thanks!

**Comment by EverStarck** [comment]
> > Hello and thank you for the library it looks awesome.
> > Is there a way to have the animation on page load as well? Not only when changing the value.
> > Thanks!
> 
> ![image](https://private-user-images.githubusercontent.com/15698245/360412954-b7387e2b-0ff9-40b9-a0c9-c2e2b64c2654.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNDg2NzEsIm5iZiI6MTcyNDM0ODM3MSwicGF0aCI6Ii8xNTY5ODI0NS8zNjA0MTI5NTQtYjczODdlMmItMGZmOS00MGI5LWEwYzktYzJlMmI2NGMyNjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE3MzkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyNTcyMDFiYzg4NDA3NTBjMjUyM2MwYzA0NTM5ZGYyNWVhNmQ4ZmE4NmU0NzA5ZDNiYWRiZjEwZWVmZWJlNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X1zJnjrkhvb6O5caYESBq048E7k0VAe1oM2KFLqctps)

bro wtf is this, learn to copy and past code pls

**Comment by dogfootruler-kr** [comment]
Thanks @kaitoukid-1412 !
